apiVersion: apps/v1
kind: Deployment
metadata:
  name: jousefor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jousefor
  template:
    metadata:
      labels:
        app: jousefor
    spec:
      containers:
      - image: okteto.dev/jousefor:latest
        name: jousefor
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "317b590f-1415-4a0b-906e-fb1e00465e07"
        - name: Vless_Path
          value: "/v8l555"
        - name: Vmess_UUID
          value: "317b590f-1415-4a0b-906e-fb1e00465e07"
        - name: Vmess_Path
          value: "/vm3866"
        - name: Share_Path
          value: "/v2link"
